BEGIN;

CREATE DOMAIN text_domain AS 
   TEXT CHECK (value ~ '^[ a-zA-Z0-9\-_]{1,30}$'); --^[ a-zA-Z0-9\-_éè'àùçùîë]{1,30}$

CREATE DOMAIN email_domain AS 
   TEXT CHECK (value ~ '^[A-Za-z0-9+_.-]+@(.+)$');


CREATE TABLE IF NOT EXISTS "continent" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NOT NULL
);


INSERT INTO "continent"("id", "label") 
VALUES 
(1, 'afrique'),
(2, 'amerique'),
(3, 'asie'),
(4, 'europe');


CREATE TABLE IF NOT EXISTS "level" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label" TEXT NOT NULL  
);


INSERT INTO "level"("id", "label") 
VALUES 
(1, 'easy'),
(2, 'medium'),
(3, 'hard');


CREATE TABLE IF NOT EXISTS "country" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "short_name" TEXT NOT NULL,
    "full_name" TEXT,
    "capital" TEXT NOT NULL,
    "continent_id" INTEGER NOT NULL REFERENCES "continent"("id"),
    "level_id" INTEGER NOT NULL REFERENCES "level"("id")
);


CREATE TABLE "user" (
    "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "email" email_domain NOT NULL UNIQUE, 
    "password" TEXT NOT NULL, 
    "username" text_domain NOT NULL, 
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE, 
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMIT;